service: plantuml-serverless

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  stage: dev
  profile: core
  cfLogs: true
  timeout: 40
  environment:
    stage: ${self:custom.stage}

plugins:
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    plantuml: plant-aws.diagrams.net
    dev: plant-aws-dev.diagrams.net
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: plant-aws-dev.diagrams.net
    basePath: ''
    stage: "${self:custom.stage}"
    createRoute53Record: true
  apigwBinary:
    types:
      - '*/*'

package:
  artifact: target/plantuml-serverless-0.0.7-DRAWIO.jar

functions:
  ui:
    handler: com.nitor.plantuml.lambda.UIHandler
    events:
      - http:
          path: /
          method: get
          integration: lambda-proxy
          cors: true
  png:
    handler: com.nitor.plantuml.lambda.PngHandler
    events:
      - http:
          path: png/{encodedUml}
          method: get
          integration: lambda-proxy
          cors: true
  img:
    handler: com.nitor.plantuml.lambda.PngHandler
    events:
      - http:
          path: img/{encodedUml}
          method: get
          integration: lambda-proxy
          cors: true
          contentHandling: CONVERT_TO_BINARY
  svg:
    handler: com.nitor.plantuml.lambda.SvgHandler
    events:
      - http:
          path: svg/{encodedUml}
          method: get
          integration: lambda-proxy
          cors: true
          contentHandling: CONVERT_TO_BINARY
  txt:
    handler: com.nitor.plantuml.lambda.TxtHandler
    events:
      - http:
          path: txt/{encodedUml}
          method: get
          integration: lambda-proxy
          cors: true
          contentHandling: CONVERT_TO_BINARY
  map:
    handler: com.nitor.plantuml.lambda.MapHandler
    events:
      - http:
          path: map/{encodedUml}
          method: get
          integration: lambda-proxy
          cors: true
          contentHandling: CONVERT_TO_BINARY
  check:
    handler: com.nitor.plantuml.lambda.SyntaxHandler
    events:
      - http:
          path: check/{encodedUml}
          method: get
          integration: lambda-proxy
          cors: true
          contentHandling: CONVERT_TO_BINARY
